### ISSUE TITLE
macOs Safari 15 automated tests detected as Private Mode

### ISSUE THREAD

**Issue by sandrolain** [Joe12387/detectIncognito#3]
Hello,
thank's for your job. It is currently the only library that works on all versions of all major vendors.

In my job I have to integrate the control on the verification of the private mode through automated tests using webdriver.io and selenium-standalone.
While testing with Safari 15 on macOS I found that the library detects the browser as private mode even though it is not.
For other browsers such as Chrome, Firefox and Edge / IE the detection occurs correctly.

**Comment by Joe12387** [comment]
Hi.

I believe this is occurring because push notifications are disabled. We detect private mode in Safari for macOS by calling safari.pushNotification.requestPermission() and grabbing the error message. In normal browsing the error is "Push notification prompting can only be done from a user gesture" while private mode returns "Push notification prompting has been disabled."

I'm unfortunately not too familiar with Selenium on Safari and haven't tested this, but I'm assuming push notifications are disabled in automated tests. If that's the case, barring the discovery of a different method of detecting private mode in Safari for macOS, there's unfortunately not much that can be done about this at this time.

**Comment by Joe12387** [comment]
The project no longer depends on whether push notifications are disabled to function. It is assumed that this fixes this issue.
