### ISSUE TITLE
Having this as a promise module

### ISSUE THREAD

**Issue by orangecoloured** [Joe12387/detectIncognito#4]
Do you plan making this a module using promises?

Or I can create a PR with this modification.

**Comment by Joe12387** [comment]
Hello.

I considered using Promises but went against it because it would remove support for Internet Explorer and I wanted to support as many browsers as is possible. The code is more for reference purposes, but also acts as a proper library.

I decided to just make two scripts, one basic JS and one with Promises, but have no plans to do so at the moment. However, I will eventually implement it. If you wish to implement it and call it something like detectIncognito-promises.js or something like that then I'll accept that into the repo. Otherwise I'll probably do it in a few months.

Let me know, thanks.

**Comment by orangecoloured** [comment]
Ok, cool. I'll create a PR with promises soon.
