### ISSUE TITLE
iPhone QR Code scanner

### ISSUE THREAD

**Issue by danbaechtold** [Joe12387/detectIncognito#8]
Hi,
Thanks for your great work.

There is one case I'm not sure how you see it, but would help me and possibly many others a LOT:
When opening an URL from the camera app, it will open in normal Safari, either in normal or private mode (whatever was last opened). But when scanning a QR code from the quick access menu (Control Center) shortcut, it will open some single browser window without a URL bar. And this window will not share it's session with Safari, meaning that if someone is authenticated in Safari, he will not be authenticated in this session, which seems to me to be very similar like being in Incognito mode.
Is this something your script could detect as well?
Thank you

**Comment by Joe12387** [comment]
Hi there.

I believe you're referring to webview? I tried scanning a QR code from control center and it's not opening in webview for me, so I can't really test this. Perhaps this is because I have other browsers installed. Regardless, I believe that webview in iOS will have a user agent that lacks "Safari" in the string. I'm not aware of a way to do this without checking the user agent string. You can't really change the user agent on iOS anyway so this should be sufficient.

Hope this is helpful.

**Comment by danbaechtold** [comment]
Hi,
Yes if you have another default browser set, then the there is no issue as both ways it will open in the new default browser.
Thanks for the suggestion, I tried, but unfortunately it's the same UA..
But thanks for your help anyway.
